// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC5k0i0minN6ToLzNpLxX1KG-WnlItM5G8',
    appId: '1:1035872171391:web:8ff635164aed4b6055164a',
    messagingSenderId: '1035872171391',
    projectId: 'matrixgpt-chat-to-invest',
    authDomain: 'matrixgpt-chat-to-invest.firebaseapp.com',
    storageBucket: 'matrixgpt-chat-to-invest.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA8rRZXJMVqaTp5UOW8zMcGj9wNs8G2VQw',
    appId: '1:1035872171391:android:0fb5a2a9a1dc211d55164a',
    messagingSenderId: '1035872171391',
    projectId: 'matrixgpt-chat-to-invest',
    storageBucket: 'matrixgpt-chat-to-invest.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBn_p-Yk-SiTCP4KJG_6TF2pX_mN7z5qU0',
    appId: '1:1035872171391:ios:7c7d0bcaf4e4ee7355164a',
    messagingSenderId: '1035872171391',
    projectId: 'matrixgpt-chat-to-invest',
    storageBucket: 'matrixgpt-chat-to-invest.appspot.com',
    iosClientId: '1035872171391-iei1s7ohkbrgv0o8q7gil1vfqn69rt2u.apps.googleusercontent.com',
    iosBundleId: 'com.wewehao.aichat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBn_p-Yk-SiTCP4KJG_6TF2pX_mN7z5qU0',
    appId: '1:1035872171391:ios:49345667ce590f9155164a',
    messagingSenderId: '1035872171391',
    projectId: 'matrixgpt-chat-to-invest',
    storageBucket: 'matrixgpt-chat-to-invest.appspot.com',
    iosClientId: '1035872171391-stc7lloi43a17n8rv8eapqa4hg3i9mas.apps.googleusercontent.com',
    iosBundleId: 'com.wewehao.flutterChatgptMatrix',
  );
}
